### ISSUE TITLE
Best way to update main.rs config changes?

### ISSUE THREAD

**Issue by frankievalentine** [ShadowArcanist/Blaze#8]
Doesn't seem like the config is updating on server restart or systemctl restart. What is the best way to update config changes?

**Comment by shadowalyxia** [comment]
Hi @frankievalentine run this command from your home directory`cd /opt/Blaze && cargo build --release && sudo systemctl restart blaze && sudo systemctl status blaze`

This will update the service by rebuilding the Rust project and restarting it. If that doesn’t fix the problem, reinstall by running the uninstall script and then the setup script.

**Comment by frankievalentine** [comment]
> Hi @frankievalentine run this command from your home directory`cd /opt/Blaze && cargo build --release && sudo systemctl restart blaze && sudo systemctl status blaze`
> 
> This will update the service by rebuilding the Rust project and restarting it. If that doesn’t fix the problem, reinstall by running the uninstall script and then the setup script.

Thank you!
